name: CI Checks

on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go get -t ./...

      - name: Run tests
        run: make test

      - name: Coverage check
        run: make coverage

      - name: Generate report
        run: make report

      - name: Copy report to report directory
        run: |
          mkdir reports
          cp cover.html reports/.

      - name: Archive report
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports

  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Copy Files
        run: |
             mkdir  artifacts
             cp api artifacts/.

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
            name: api
            path: artifacts

  deliver:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: api

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            api
